---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: lang/mruby
    tag: build
inputs:
  - name: ci
  - name: src
outputs:
  - name: compiled
run:
  path: ci/scripts/mruby/compile
  args:
    - src
    - compiled
