---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: package/git
inputs:
  - name: ci
  - name: src
outputs:
  - name: metadata
run:
  path: ci/scripts/mruby/extract-metadata
  args:
    - src
    - metadata
