---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: contains/upx
inputs:
  - name: ci
  - name: stripped
outputs:
  - name: packed
run:
  path: ci/scripts/mruby/pack
  args:
    - stripped
    - packed
