---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: colstrom/alpine
inputs:
  - name: ci
  - name: packed
outputs:
  - name: prepared
run:
  path: ci/scripts/mruby/prepare
  args:
    - ci
    - packed
    - prepared
