---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: package/binutils
inputs:
  - name: ci
  - name: compiled
outputs:
  - name: stripped
run:
  path: ci/scripts/mruby/strip
  args:
    - compiled
    - stripped
